# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ENV
            . ENV/bin/activate
            pip install -r requirements.txt
      - run:
          name: run unit test
          command: |
            . ENV/bin/activate
            cd simple_register_django && python manage.py test
      - run:
          name: build image
          command: |
            docker build -t mixkungz/django-simple-register:live .
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push mixkungz/django-simple-register:live
